version: 2.1

jobs:
  build-and-push:
    docker:
      - image: blackarchlinux/blackarch:base-devel
        environment:
          options: --privileged
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pacman -Syyu git --noconfirm --quiet --needed
      - run:
          name: Build ArchISO
          command: |
            sudo git clone https://github.com/MikuX-Dev/blackarch-iso 
            sudo mkdir -p work out 
            sudo mkarchiso -v -r -w work -o out blackarch-iso/slim-iso
      - store_artifacts:
          path: out/*.iso
          destination: Blackarch-slim-iso and log

workflows:
  version: 2.1
  build-and-push-workflow:
    jobs:
      - build-and-push
