version: 2.1

jobs:
  build-and-push:
    docker:
      - image: mikuxdev/archiso-builder:latest
        environment:
          options: --privileged
    steps:
      - run:
          name: Create new user with sudo permission
          command: |
            useradd -m newuser
            echo 'newuser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pacman -Syy
      - run:
          name: Build ArchISO
          command: |
            sudo -u newuser git clone https://github.com/MikuX-Dev/blackarch-iso 
            sudo -u newuser mkdir -p work out 
            sudo -u newuser mkarchiso -v -r -w work -o out blackarch-iso/slim-iso
      - store_artifacts:
          path: out/*.iso
          destination: Blackarch-slim-iso and log

workflows:
  version: 2.1
  build-and-push-workflow:
    jobs:
      - build-and-push
