version: 2.1

jobs:
  build-and-push:
    docker:
      - image: archlinux:base-devel
        environment:
          options: --privileged
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo pacman-key --init 
            sudo pacman-key --populate 
            sudo sed -i "s/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g" /etc/locale.gen 
            sudo locale-gen 
            sudo echo "LANG=en_US.UTF-8" > /etc/locale.conf
            sudo echo 'KEYMAP=us' > /etc/vconsole.conf
            sudo curl -O https://blackarch.org/strap.sh
            sudo chmod +x strap.sh 
            sudo bash strap.sh --noconfirm --quiet 
            # sudo curl https://raw.githubusercontent.com/MikuX-Dev/blackarch-iso/master/pacman.conf -o /etc/pacman.conf
            sudo curl https://raw.githubusercontent.com/MikuX-Dev/docker-archiso/main/blackarch-mirrorlist -o /etc/pacman.d/blackarch-mirrorlist 
            sudo sh -c "curl https://archlinux.org/mirrorlist/\?country=all\&protocol=http\&protocol=https\&ip_version=4\&ip_version=6\&use_mirror_status=on -o /etc/pacman.d/mirrorlist && sed -i 's/#S/S/g' /etc/pacman.d/mirrorlist"
            sudo pacman -Syyu
            sudo pacman -Syy --noconfirm --quiet --needed base base-devel archiso mkinitcpio-archiso devtools dosfstools mtools fakeroot fakechroot linux-firmware net-tools ntp git docker docker-compose docker-buildx docker-scan docker-machine gcc perl automake curl sed arch-install-scripts squashfs-tools libisoburn btrfs-progs lynx mkinitcpio-nfs-utils glibc
            sudo pacman -Scc --noconfirm --quiet
            sudo rm -rf /var/cache/pacman/pkg/* 
      - run:
          name: Build ArchISO
          command: |
            sudo pacman -Scc --noconfirm --quiet
            sudo rm -rf /var/cache/pacman/pkg/* 
            sudo git clone https://github.com/MikuX-Dev/blackarch-iso 
            sudo mkdir -p work out 
            sudo mkarchiso -v -r -w work -o out blackarch-iso/slim-iso
      - store_artifacts:
          path: out/*.iso
          destination: Blackarch-slim-iso and log

workflows:
  version: 2.1
  build-and-push-workflow:
    jobs:
      - build-and-push
