version: 2.1

jobs:
  build-and-push:
    docker:
      - image: archlinux:base-devel
        environment:
          options: --privileged
    steps:
      - checkout
      - setup_remote_docker:  # This step allows Docker commands to run inside the Docker image
          version: 20.10.8  # Use the appropriate Docker version
      - run:
          name: Create user and set permissions
          command: |
            useradd -m -G sudo,wheel builder -s /bin/bash 
            echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
            chmod 0440 /etc/sudoers.d/builder
            su - builder  
      - run:
          name: Install dependencies
          command: |
            sudo curl -O https://blackarch.org/strap.sh | sh
            if grep -q "\[multilib\]" /etc/pacman.conf; then
              sudo sed -i '/^\[multilib\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
            else
              echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a /etc/pacman.conf
            fi
            if grep -q "\[community\]" /etc/pacman.conf; then
              sudo sed -i '/^\[community\]/,/Include = \/etc\/pacman.d\/mirrorlist/ s/^#//' /etc/pacman.conf
            else
              echo -e "[community]\nInclude = /etc/pacman.d/mirrorlist" | sudo tee -a /etc/pacman.conf
            fi
            sudo sh -c "curl https://archlinux.org/mirrorlist/\?country=all\&protocol=http\&protocol=https\&ip_version=4\&ip_version=6\&use_mirror_status=on -o /etc/pacman.d/mirrorlist && sed -i 's/#S/S/g' /etc/pacman.d/mirrorlist"
            sudo pacman -Syyu --noconfirm --quiet
            sudo pacman -S --noconfirm --quiet --needed base base-devel archiso mkinitcpio-archiso devtools dosfstools mtools fakeroot fakechroot linux-firmware net-tools ntp git gcc perl automake curl sed arch-install-scripts squashfs-tools libisoburn btrfs-progs lynx mkinitcpio-nfs-utils glibc
            sudo pacman -Scc --noconfirm --quiet
            sudo rm -rf /var/cache/pacman/pkg/* 
      - run:
          name: Build ArchISO
          command: |
            sudo git clone https://github.com/MikuX-Dev/blackarch-iso 
            sudo mkdir -p work out 
            sudo mkarchiso -v -r -w work -o out blackarch-iso/slim-iso
      - store_artifacts:
          path: out/*.iso
          destination: Blackarch-slim-iso and log

workflows:
  version: 2.1
  build-and-push-workflow:
    jobs:
      - build-and-push
