name: Build and Push Arch ISO Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: mikuxdev/archiso-builder
      options: --privileged

    steps:
      - name: Checkout files
        uses: actions/checkout@v3
 
    #   - name: user change
    #     run: su - builder

      - name: Install dependencies
        run: | 
          pacman -Syy

      - name: Build ArchISO
        run: |
          git clone https://github.com/MikuX-Dev/blackarch-iso 
          mkdir -p work out 
          mkarchiso -v -r -w work -o out blackarch-iso/slim-iso || su - builder | mkarchiso -v -r -w work -o out blackarch-iso/slim-iso

      - name: Upload ISOs
        uses: actions/upload-artifact@v2
        with:
          name: Blackarch-slim-iso 
          path: out/*.iso
